// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB_JclSSf0kl740ScivfdwbqQFm8pBzRg',
    appId: '1:664005681505:web:150ca4d6ac3bc62a7ca520',
    messagingSenderId: '664005681505',
    projectId: 'graduate-40eb5',
    authDomain: 'graduate-40eb5.firebaseapp.com',
    storageBucket: 'graduate-40eb5.appspot.com',
    measurementId: 'G-G318P2GKJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhQYtQG4er2ILXk9iWnj91BpdXLKsZncg',
    appId: '1:664005681505:android:22198e5b16a4a5837ca520',
    messagingSenderId: '664005681505',
    projectId: 'graduate-40eb5',
    storageBucket: 'graduate-40eb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUi3MYGHrX4H_xEL3WrRgGeRCIaLqQg-c',
    appId: '1:664005681505:ios:f3f116ae30fac36e7ca520',
    messagingSenderId: '664005681505',
    projectId: 'graduate-40eb5',
    storageBucket: 'graduate-40eb5.appspot.com',
    iosBundleId: 'com.example.graduate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUi3MYGHrX4H_xEL3WrRgGeRCIaLqQg-c',
    appId: '1:664005681505:ios:158a367029f7fee77ca520',
    messagingSenderId: '664005681505',
    projectId: 'graduate-40eb5',
    storageBucket: 'graduate-40eb5.appspot.com',
    iosBundleId: 'com.example.graduate.RunnerTests',
  );
}
